/* Generated by makegdbusalias.pl */

#ifndef DISABLE_VISIBILITY

#include "glib.h"

#ifdef G_HAVE_GNUC_VISIBILITY

#undef IN_FILE
#define IN_FILE defined

#undef IN_HEADER
#define IN_HEADER(x) 1

#if IN_HEADER(__G_DBUS_CONNECTION_H__)
#if IN_FILE(__G_DBUS_CONNECTION_C__)
#undef g_dbus_connection_get_type 
extern __typeof (g_dbus_connection_get_type) g_dbus_connection_get_type __attribute((alias("IA__g_dbus_connection_get_type"), visibility("default")));

#undef g_dbus_connection_bus_get 
extern __typeof (g_dbus_connection_bus_get) g_dbus_connection_bus_get __attribute((alias("IA__g_dbus_connection_bus_get"), visibility("default")));

#undef g_dbus_connection_bus_get_finish 
extern __typeof (g_dbus_connection_bus_get_finish) g_dbus_connection_bus_get_finish __attribute((alias("IA__g_dbus_connection_bus_get_finish"), visibility("default")));

#undef g_dbus_connection_bus_get_sync 
extern __typeof (g_dbus_connection_bus_get_sync) g_dbus_connection_bus_get_sync __attribute((alias("IA__g_dbus_connection_bus_get_sync"), visibility("default")));

#undef g_dbus_connection_bus_get_private_sync 
extern __typeof (g_dbus_connection_bus_get_private_sync) g_dbus_connection_bus_get_private_sync __attribute((alias("IA__g_dbus_connection_bus_get_private_sync"), visibility("default")));

#undef g_dbus_connection_get_unique_name 
extern __typeof (g_dbus_connection_get_unique_name) g_dbus_connection_get_unique_name __attribute((alias("IA__g_dbus_connection_get_unique_name"), visibility("default")));

#undef g_dbus_connection_get_is_disconnected 
extern __typeof (g_dbus_connection_get_is_disconnected) g_dbus_connection_get_is_disconnected __attribute((alias("IA__g_dbus_connection_get_is_disconnected"), visibility("default")));

#undef g_dbus_connection_set_exit_on_disconnect 
extern __typeof (g_dbus_connection_set_exit_on_disconnect) g_dbus_connection_set_exit_on_disconnect __attribute((alias("IA__g_dbus_connection_set_exit_on_disconnect"), visibility("default")));

#undef g_dbus_connection_signal_subscribe 
extern __typeof (g_dbus_connection_signal_subscribe) g_dbus_connection_signal_subscribe __attribute((alias("IA__g_dbus_connection_signal_subscribe"), visibility("default")));

#undef g_dbus_connection_signal_unsubscribe 
extern __typeof (g_dbus_connection_signal_unsubscribe) g_dbus_connection_signal_unsubscribe __attribute((alias("IA__g_dbus_connection_signal_unsubscribe"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_CONNECTION_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_CONNECTION_C__)
#undef g_dbus_connection_get_dbus_1_connection 
extern __typeof (g_dbus_connection_get_dbus_1_connection) g_dbus_connection_get_dbus_1_connection __attribute((alias("IA__g_dbus_connection_get_dbus_1_connection"), visibility("default")));

#undef g_dbus_connection_send_dbus_1_message 
extern __typeof (g_dbus_connection_send_dbus_1_message) g_dbus_connection_send_dbus_1_message __attribute((alias("IA__g_dbus_connection_send_dbus_1_message"), visibility("default")));

#undef g_dbus_connection_send_dbus_1_message_with_reply 
extern __typeof (g_dbus_connection_send_dbus_1_message_with_reply) g_dbus_connection_send_dbus_1_message_with_reply __attribute((alias("IA__g_dbus_connection_send_dbus_1_message_with_reply"), visibility("default")));

#undef g_dbus_connection_send_dbus_1_message_with_reply_finish 
extern __typeof (g_dbus_connection_send_dbus_1_message_with_reply_finish) g_dbus_connection_send_dbus_1_message_with_reply_finish __attribute((alias("IA__g_dbus_connection_send_dbus_1_message_with_reply_finish"), visibility("default")));

#undef g_dbus_connection_send_dbus_1_message_with_reply_sync 
extern __typeof (g_dbus_connection_send_dbus_1_message_with_reply_sync) g_dbus_connection_send_dbus_1_message_with_reply_sync __attribute((alias("IA__g_dbus_connection_send_dbus_1_message_with_reply_sync"), visibility("default")));

#undef g_dbus_connection_dbus_1_signal_subscribe 
extern __typeof (g_dbus_connection_dbus_1_signal_subscribe) g_dbus_connection_dbus_1_signal_subscribe __attribute((alias("IA__g_dbus_connection_dbus_1_signal_subscribe"), visibility("default")));

#undef g_dbus_connection_dbus_1_signal_unsubscribe 
extern __typeof (g_dbus_connection_dbus_1_signal_unsubscribe) g_dbus_connection_dbus_1_signal_unsubscribe __attribute((alias("IA__g_dbus_connection_dbus_1_signal_unsubscribe"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_C_TYPE_MAPPING_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_C_TYPE_MAPPING_C__)
#undef g_dbus_c_type_mapping_get_value_from_iter 
extern __typeof (g_dbus_c_type_mapping_get_value_from_iter) g_dbus_c_type_mapping_get_value_from_iter __attribute((alias("IA__g_dbus_c_type_mapping_get_value_from_iter"), visibility("default")));

#undef g_dbus_c_type_mapping_append_value_to_iter 
extern __typeof (g_dbus_c_type_mapping_append_value_to_iter) g_dbus_c_type_mapping_append_value_to_iter __attribute((alias("IA__g_dbus_c_type_mapping_append_value_to_iter"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_MAINLOOP_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_MAINLOOP_C__)
#undef g_dbus_integrate_dbus_1_connection 
extern __typeof (g_dbus_integrate_dbus_1_connection) g_dbus_integrate_dbus_1_connection __attribute((alias("IA__g_dbus_integrate_dbus_1_connection"), visibility("default")));

#undef g_dbus_unintegrate_dbus_1_connection 
extern __typeof (g_dbus_unintegrate_dbus_1_connection) g_dbus_unintegrate_dbus_1_connection __attribute((alias("IA__g_dbus_unintegrate_dbus_1_connection"), visibility("default")));

#undef g_dbus_integrate_dbus_1_server 
extern __typeof (g_dbus_integrate_dbus_1_server) g_dbus_integrate_dbus_1_server __attribute((alias("IA__g_dbus_integrate_dbus_1_server"), visibility("default")));

#undef g_dbus_unintegrate_dbus_1_server 
extern __typeof (g_dbus_unintegrate_dbus_1_server) g_dbus_unintegrate_dbus_1_server __attribute((alias("IA__g_dbus_unintegrate_dbus_1_server"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_ENUM_TYPES_H__)
#if IN_FILE(__G_DBUS_ENUM_TYPES_C__)
#undef g_dbus_error_get_type 
extern __typeof (g_dbus_error_get_type) g_dbus_error_get_type __attribute((alias("IA__g_dbus_error_get_type"), visibility("default")));

#undef g_bus_type_get_type 
extern __typeof (g_bus_type_get_type) g_bus_type_get_type __attribute((alias("IA__g_bus_type_get_type"), visibility("default")));

#undef g_bus_name_owner_flags_get_type 
extern __typeof (g_bus_name_owner_flags_get_type) g_bus_name_owner_flags_get_type __attribute((alias("IA__g_bus_name_owner_flags_get_type"), visibility("default")));

#undef g_dbus_proxy_flags_get_type 
extern __typeof (g_dbus_proxy_flags_get_type) g_dbus_proxy_flags_get_type __attribute((alias("IA__g_dbus_proxy_flags_get_type"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_ERROR_H__)
#if IN_FILE(__G_DBUS_ERROR_C__)
#undef g_dbus_error_quark 
extern __typeof (g_dbus_error_quark) g_dbus_error_quark __attribute((alias("IA__g_dbus_error_quark"), visibility("default")));

#undef g_dbus_error_get_remote_exception 
extern __typeof (g_dbus_error_get_remote_exception) g_dbus_error_get_remote_exception __attribute((alias("IA__g_dbus_error_get_remote_exception"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_ERROR_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_ERROR_C__)
#undef g_dbus_error_new_for_dbus_error 
extern __typeof (g_dbus_error_new_for_dbus_error) g_dbus_error_new_for_dbus_error __attribute((alias("IA__g_dbus_error_new_for_dbus_error"), visibility("default")));

#undef g_dbus_error_new_for_dbus_error_valist 
extern __typeof (g_dbus_error_new_for_dbus_error_valist) g_dbus_error_new_for_dbus_error_valist __attribute((alias("IA__g_dbus_error_new_for_dbus_error_valist"), visibility("default")));

#undef g_dbus_error_new_for_gerror 
extern __typeof (g_dbus_error_new_for_gerror) g_dbus_error_new_for_gerror __attribute((alias("IA__g_dbus_error_new_for_gerror"), visibility("default")));

#undef g_dbus_error_set_dbus_error 
extern __typeof (g_dbus_error_set_dbus_error) g_dbus_error_set_dbus_error __attribute((alias("IA__g_dbus_error_set_dbus_error"), visibility("default")));

#undef g_dbus_error_set_dbus_error_valist 
extern __typeof (g_dbus_error_set_dbus_error_valist) g_dbus_error_set_dbus_error_valist __attribute((alias("IA__g_dbus_error_set_dbus_error_valist"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_NAME_WATCHING_H__)
#if IN_FILE(__G_DBUS_NAME_WATCHING_C__)
#undef g_bus_watch_name 
extern __typeof (g_bus_watch_name) g_bus_watch_name __attribute((alias("IA__g_bus_watch_name"), visibility("default")));

#undef g_bus_unwatch_name 
extern __typeof (g_bus_unwatch_name) g_bus_unwatch_name __attribute((alias("IA__g_bus_unwatch_name"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_PROXY_WATCHING_H__)
#if IN_FILE(__G_DBUS_PROXY_WATCHING_C__)
#undef g_bus_watch_proxy 
extern __typeof (g_bus_watch_proxy) g_bus_watch_proxy __attribute((alias("IA__g_bus_watch_proxy"), visibility("default")));

#undef g_bus_unwatch_proxy 
extern __typeof (g_bus_unwatch_proxy) g_bus_unwatch_proxy __attribute((alias("IA__g_bus_unwatch_proxy"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_NAME_OWNING_H__)
#if IN_FILE(__G_DBUS_NAME_OWNING_C__)
#undef g_bus_own_name 
extern __typeof (g_bus_own_name) g_bus_own_name __attribute((alias("IA__g_bus_own_name"), visibility("default")));

#undef g_bus_own_name_on_connection 
extern __typeof (g_bus_own_name_on_connection) g_bus_own_name_on_connection __attribute((alias("IA__g_bus_own_name_on_connection"), visibility("default")));

#undef g_bus_unown_name 
extern __typeof (g_bus_unown_name) g_bus_unown_name __attribute((alias("IA__g_bus_unown_name"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_PROXY_H__)
#if IN_FILE(__G_DBUS_PROXY_C__)
#undef g_dbus_proxy_get_type 
extern __typeof (g_dbus_proxy_get_type) g_dbus_proxy_get_type __attribute((alias("IA__g_dbus_proxy_get_type"), visibility("default")));

#undef g_dbus_proxy_new 
extern __typeof (g_dbus_proxy_new) g_dbus_proxy_new __attribute((alias("IA__g_dbus_proxy_new"), visibility("default")));

#undef g_dbus_proxy_new_finish 
extern __typeof (g_dbus_proxy_new_finish) g_dbus_proxy_new_finish __attribute((alias("IA__g_dbus_proxy_new_finish"), visibility("default")));

#undef g_dbus_proxy_new_sync 
extern __typeof (g_dbus_proxy_new_sync) g_dbus_proxy_new_sync __attribute((alias("IA__g_dbus_proxy_new_sync"), visibility("default")));

#undef g_dbus_proxy_get_flags 
extern __typeof (g_dbus_proxy_get_flags) g_dbus_proxy_get_flags __attribute((alias("IA__g_dbus_proxy_get_flags"), visibility("default")));

#undef g_dbus_proxy_get_unique_bus_name 
extern __typeof (g_dbus_proxy_get_unique_bus_name) g_dbus_proxy_get_unique_bus_name __attribute((alias("IA__g_dbus_proxy_get_unique_bus_name"), visibility("default")));

#undef g_dbus_proxy_get_object_path 
extern __typeof (g_dbus_proxy_get_object_path) g_dbus_proxy_get_object_path __attribute((alias("IA__g_dbus_proxy_get_object_path"), visibility("default")));

#undef g_dbus_proxy_get_interface_name 
extern __typeof (g_dbus_proxy_get_interface_name) g_dbus_proxy_get_interface_name __attribute((alias("IA__g_dbus_proxy_get_interface_name"), visibility("default")));

#undef g_dbus_proxy_get_connection 
extern __typeof (g_dbus_proxy_get_connection) g_dbus_proxy_get_connection __attribute((alias("IA__g_dbus_proxy_get_connection"), visibility("default")));

#undef g_dbus_proxy_invoke_method 
extern __typeof (g_dbus_proxy_invoke_method) g_dbus_proxy_invoke_method __attribute((alias("IA__g_dbus_proxy_invoke_method"), visibility("default")));

#undef g_dbus_proxy_invoke_method_finish 
extern __typeof (g_dbus_proxy_invoke_method_finish) g_dbus_proxy_invoke_method_finish __attribute((alias("IA__g_dbus_proxy_invoke_method_finish"), visibility("default")));

#undef g_dbus_proxy_invoke_method_sync 
extern __typeof (g_dbus_proxy_invoke_method_sync) g_dbus_proxy_invoke_method_sync __attribute((alias("IA__g_dbus_proxy_invoke_method_sync"), visibility("default")));

#undef g_dbus_proxy_get_cached_property 
extern __typeof (g_dbus_proxy_get_cached_property) g_dbus_proxy_get_cached_property __attribute((alias("IA__g_dbus_proxy_get_cached_property"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_STRUCTURE_H__)
#if IN_FILE(__G_DBUS_STRUCTURE_C__)
#undef g_dbus_structure_get_type 
extern __typeof (g_dbus_structure_get_type) g_dbus_structure_get_type __attribute((alias("IA__g_dbus_structure_get_type"), visibility("default")));

#undef g_dbus_structure_equal 
extern __typeof (g_dbus_structure_equal) g_dbus_structure_equal __attribute((alias("IA__g_dbus_structure_equal"), visibility("default")));

#undef g_dbus_structure_get_element 
extern __typeof (g_dbus_structure_get_element) g_dbus_structure_get_element __attribute((alias("IA__g_dbus_structure_get_element"), visibility("default")));

#undef g_dbus_structure_get_num_elements 
extern __typeof (g_dbus_structure_get_num_elements) g_dbus_structure_get_num_elements __attribute((alias("IA__g_dbus_structure_get_num_elements"), visibility("default")));

#undef g_dbus_structure_get_signature 
extern __typeof (g_dbus_structure_get_signature) g_dbus_structure_get_signature __attribute((alias("IA__g_dbus_structure_get_signature"), visibility("default")));

#undef g_dbus_structure_get_signature_for_element 
extern __typeof (g_dbus_structure_get_signature_for_element) g_dbus_structure_get_signature_for_element __attribute((alias("IA__g_dbus_structure_get_signature_for_element"), visibility("default")));

#undef g_dbus_structure_new 
extern __typeof (g_dbus_structure_new) g_dbus_structure_new __attribute((alias("IA__g_dbus_structure_new"), visibility("default")));

#undef g_dbus_structure_set_element 
extern __typeof (g_dbus_structure_set_element) g_dbus_structure_set_element __attribute((alias("IA__g_dbus_structure_set_element"), visibility("default")));

#endif
#endif
#if IN_HEADER(__G_DBUS_VARIANT_H__)
#if IN_FILE(__G_DBUS_VARIANT_C__)
#undef g_dbus_variant_get_type 
extern __typeof (g_dbus_variant_get_type) g_dbus_variant_get_type __attribute((alias("IA__g_dbus_variant_get_type"), visibility("default")));

#undef g_dbus_variant_equal 
extern __typeof (g_dbus_variant_equal) g_dbus_variant_equal __attribute((alias("IA__g_dbus_variant_equal"), visibility("default")));

#undef g_dbus_variant_get_array 
extern __typeof (g_dbus_variant_get_array) g_dbus_variant_get_array __attribute((alias("IA__g_dbus_variant_get_array"), visibility("default")));

#undef g_dbus_variant_get_boolean 
extern __typeof (g_dbus_variant_get_boolean) g_dbus_variant_get_boolean __attribute((alias("IA__g_dbus_variant_get_boolean"), visibility("default")));

#undef g_dbus_variant_get_byte 
extern __typeof (g_dbus_variant_get_byte) g_dbus_variant_get_byte __attribute((alias("IA__g_dbus_variant_get_byte"), visibility("default")));

#undef g_dbus_variant_get_double 
extern __typeof (g_dbus_variant_get_double) g_dbus_variant_get_double __attribute((alias("IA__g_dbus_variant_get_double"), visibility("default")));

#undef g_dbus_variant_get_hash_table 
extern __typeof (g_dbus_variant_get_hash_table) g_dbus_variant_get_hash_table __attribute((alias("IA__g_dbus_variant_get_hash_table"), visibility("default")));

#undef g_dbus_variant_get_int 
extern __typeof (g_dbus_variant_get_int) g_dbus_variant_get_int __attribute((alias("IA__g_dbus_variant_get_int"), visibility("default")));

#undef g_dbus_variant_get_int16 
extern __typeof (g_dbus_variant_get_int16) g_dbus_variant_get_int16 __attribute((alias("IA__g_dbus_variant_get_int16"), visibility("default")));

#undef g_dbus_variant_get_int64 
extern __typeof (g_dbus_variant_get_int64) g_dbus_variant_get_int64 __attribute((alias("IA__g_dbus_variant_get_int64"), visibility("default")));

#undef g_dbus_variant_get_object_path 
extern __typeof (g_dbus_variant_get_object_path) g_dbus_variant_get_object_path __attribute((alias("IA__g_dbus_variant_get_object_path"), visibility("default")));

#undef g_dbus_variant_get_object_path_array 
extern __typeof (g_dbus_variant_get_object_path_array) g_dbus_variant_get_object_path_array __attribute((alias("IA__g_dbus_variant_get_object_path_array"), visibility("default")));

#undef g_dbus_variant_get_ptr_array 
extern __typeof (g_dbus_variant_get_ptr_array) g_dbus_variant_get_ptr_array __attribute((alias("IA__g_dbus_variant_get_ptr_array"), visibility("default")));

#undef g_dbus_variant_get_signature 
extern __typeof (g_dbus_variant_get_signature) g_dbus_variant_get_signature __attribute((alias("IA__g_dbus_variant_get_signature"), visibility("default")));

#undef g_dbus_variant_get_signature_array 
extern __typeof (g_dbus_variant_get_signature_array) g_dbus_variant_get_signature_array __attribute((alias("IA__g_dbus_variant_get_signature_array"), visibility("default")));

#undef g_dbus_variant_get_string 
extern __typeof (g_dbus_variant_get_string) g_dbus_variant_get_string __attribute((alias("IA__g_dbus_variant_get_string"), visibility("default")));

#undef g_dbus_variant_get_string_array 
extern __typeof (g_dbus_variant_get_string_array) g_dbus_variant_get_string_array __attribute((alias("IA__g_dbus_variant_get_string_array"), visibility("default")));

#undef g_dbus_variant_get_structure 
extern __typeof (g_dbus_variant_get_structure) g_dbus_variant_get_structure __attribute((alias("IA__g_dbus_variant_get_structure"), visibility("default")));

#undef g_dbus_variant_get_variant 
extern __typeof (g_dbus_variant_get_variant) g_dbus_variant_get_variant __attribute((alias("IA__g_dbus_variant_get_variant"), visibility("default")));

#undef g_dbus_variant_get_uint 
extern __typeof (g_dbus_variant_get_uint) g_dbus_variant_get_uint __attribute((alias("IA__g_dbus_variant_get_uint"), visibility("default")));

#undef g_dbus_variant_get_uint16 
extern __typeof (g_dbus_variant_get_uint16) g_dbus_variant_get_uint16 __attribute((alias("IA__g_dbus_variant_get_uint16"), visibility("default")));

#undef g_dbus_variant_get_uint64 
extern __typeof (g_dbus_variant_get_uint64) g_dbus_variant_get_uint64 __attribute((alias("IA__g_dbus_variant_get_uint64"), visibility("default")));

#undef g_dbus_variant_get_variant_signature 
extern __typeof (g_dbus_variant_get_variant_signature) g_dbus_variant_get_variant_signature __attribute((alias("IA__g_dbus_variant_get_variant_signature"), visibility("default")));

#undef g_dbus_variant_is_array 
extern __typeof (g_dbus_variant_is_array) g_dbus_variant_is_array __attribute((alias("IA__g_dbus_variant_is_array"), visibility("default")));

#undef g_dbus_variant_is_boolean 
extern __typeof (g_dbus_variant_is_boolean) g_dbus_variant_is_boolean __attribute((alias("IA__g_dbus_variant_is_boolean"), visibility("default")));

#undef g_dbus_variant_is_byte 
extern __typeof (g_dbus_variant_is_byte) g_dbus_variant_is_byte __attribute((alias("IA__g_dbus_variant_is_byte"), visibility("default")));

#undef g_dbus_variant_is_double 
extern __typeof (g_dbus_variant_is_double) g_dbus_variant_is_double __attribute((alias("IA__g_dbus_variant_is_double"), visibility("default")));

#undef g_dbus_variant_is_hash_table 
extern __typeof (g_dbus_variant_is_hash_table) g_dbus_variant_is_hash_table __attribute((alias("IA__g_dbus_variant_is_hash_table"), visibility("default")));

#undef g_dbus_variant_is_int 
extern __typeof (g_dbus_variant_is_int) g_dbus_variant_is_int __attribute((alias("IA__g_dbus_variant_is_int"), visibility("default")));

#undef g_dbus_variant_is_int16 
extern __typeof (g_dbus_variant_is_int16) g_dbus_variant_is_int16 __attribute((alias("IA__g_dbus_variant_is_int16"), visibility("default")));

#undef g_dbus_variant_is_int64 
extern __typeof (g_dbus_variant_is_int64) g_dbus_variant_is_int64 __attribute((alias("IA__g_dbus_variant_is_int64"), visibility("default")));

#undef g_dbus_variant_is_object_path 
extern __typeof (g_dbus_variant_is_object_path) g_dbus_variant_is_object_path __attribute((alias("IA__g_dbus_variant_is_object_path"), visibility("default")));

#undef g_dbus_variant_is_object_path_array 
extern __typeof (g_dbus_variant_is_object_path_array) g_dbus_variant_is_object_path_array __attribute((alias("IA__g_dbus_variant_is_object_path_array"), visibility("default")));

#undef g_dbus_variant_is_ptr_array 
extern __typeof (g_dbus_variant_is_ptr_array) g_dbus_variant_is_ptr_array __attribute((alias("IA__g_dbus_variant_is_ptr_array"), visibility("default")));

#undef g_dbus_variant_is_signature 
extern __typeof (g_dbus_variant_is_signature) g_dbus_variant_is_signature __attribute((alias("IA__g_dbus_variant_is_signature"), visibility("default")));

#undef g_dbus_variant_is_signature_array 
extern __typeof (g_dbus_variant_is_signature_array) g_dbus_variant_is_signature_array __attribute((alias("IA__g_dbus_variant_is_signature_array"), visibility("default")));

#undef g_dbus_variant_is_string 
extern __typeof (g_dbus_variant_is_string) g_dbus_variant_is_string __attribute((alias("IA__g_dbus_variant_is_string"), visibility("default")));

#undef g_dbus_variant_is_string_array 
extern __typeof (g_dbus_variant_is_string_array) g_dbus_variant_is_string_array __attribute((alias("IA__g_dbus_variant_is_string_array"), visibility("default")));

#undef g_dbus_variant_is_structure 
extern __typeof (g_dbus_variant_is_structure) g_dbus_variant_is_structure __attribute((alias("IA__g_dbus_variant_is_structure"), visibility("default")));

#undef g_dbus_variant_is_variant 
extern __typeof (g_dbus_variant_is_variant) g_dbus_variant_is_variant __attribute((alias("IA__g_dbus_variant_is_variant"), visibility("default")));

#undef g_dbus_variant_is_uint 
extern __typeof (g_dbus_variant_is_uint) g_dbus_variant_is_uint __attribute((alias("IA__g_dbus_variant_is_uint"), visibility("default")));

#undef g_dbus_variant_is_uint16 
extern __typeof (g_dbus_variant_is_uint16) g_dbus_variant_is_uint16 __attribute((alias("IA__g_dbus_variant_is_uint16"), visibility("default")));

#undef g_dbus_variant_is_uint64 
extern __typeof (g_dbus_variant_is_uint64) g_dbus_variant_is_uint64 __attribute((alias("IA__g_dbus_variant_is_uint64"), visibility("default")));

#undef g_dbus_variant_is_unset 
extern __typeof (g_dbus_variant_is_unset) g_dbus_variant_is_unset __attribute((alias("IA__g_dbus_variant_is_unset"), visibility("default")));

#undef g_dbus_variant_new 
extern __typeof (g_dbus_variant_new) g_dbus_variant_new __attribute((alias("IA__g_dbus_variant_new"), visibility("default")));

#undef g_dbus_variant_new_for_array 
extern __typeof (g_dbus_variant_new_for_array) g_dbus_variant_new_for_array __attribute((alias("IA__g_dbus_variant_new_for_array"), visibility("default")));

#undef g_dbus_variant_new_for_boolean 
extern __typeof (g_dbus_variant_new_for_boolean) g_dbus_variant_new_for_boolean __attribute((alias("IA__g_dbus_variant_new_for_boolean"), visibility("default")));

#undef g_dbus_variant_new_for_byte 
extern __typeof (g_dbus_variant_new_for_byte) g_dbus_variant_new_for_byte __attribute((alias("IA__g_dbus_variant_new_for_byte"), visibility("default")));

#undef g_dbus_variant_new_for_double 
extern __typeof (g_dbus_variant_new_for_double) g_dbus_variant_new_for_double __attribute((alias("IA__g_dbus_variant_new_for_double"), visibility("default")));

#undef g_dbus_variant_new_for_hash_table 
extern __typeof (g_dbus_variant_new_for_hash_table) g_dbus_variant_new_for_hash_table __attribute((alias("IA__g_dbus_variant_new_for_hash_table"), visibility("default")));

#undef g_dbus_variant_new_for_int 
extern __typeof (g_dbus_variant_new_for_int) g_dbus_variant_new_for_int __attribute((alias("IA__g_dbus_variant_new_for_int"), visibility("default")));

#undef g_dbus_variant_new_for_int16 
extern __typeof (g_dbus_variant_new_for_int16) g_dbus_variant_new_for_int16 __attribute((alias("IA__g_dbus_variant_new_for_int16"), visibility("default")));

#undef g_dbus_variant_new_for_int64 
extern __typeof (g_dbus_variant_new_for_int64) g_dbus_variant_new_for_int64 __attribute((alias("IA__g_dbus_variant_new_for_int64"), visibility("default")));

#undef g_dbus_variant_new_for_object_path 
extern __typeof (g_dbus_variant_new_for_object_path) g_dbus_variant_new_for_object_path __attribute((alias("IA__g_dbus_variant_new_for_object_path"), visibility("default")));

#undef g_dbus_variant_new_for_object_path_array 
extern __typeof (g_dbus_variant_new_for_object_path_array) g_dbus_variant_new_for_object_path_array __attribute((alias("IA__g_dbus_variant_new_for_object_path_array"), visibility("default")));

#undef g_dbus_variant_new_for_ptr_array 
extern __typeof (g_dbus_variant_new_for_ptr_array) g_dbus_variant_new_for_ptr_array __attribute((alias("IA__g_dbus_variant_new_for_ptr_array"), visibility("default")));

#undef g_dbus_variant_new_for_signature 
extern __typeof (g_dbus_variant_new_for_signature) g_dbus_variant_new_for_signature __attribute((alias("IA__g_dbus_variant_new_for_signature"), visibility("default")));

#undef g_dbus_variant_new_for_signature_array 
extern __typeof (g_dbus_variant_new_for_signature_array) g_dbus_variant_new_for_signature_array __attribute((alias("IA__g_dbus_variant_new_for_signature_array"), visibility("default")));

#undef g_dbus_variant_new_for_string 
extern __typeof (g_dbus_variant_new_for_string) g_dbus_variant_new_for_string __attribute((alias("IA__g_dbus_variant_new_for_string"), visibility("default")));

#undef g_dbus_variant_new_for_string_array 
extern __typeof (g_dbus_variant_new_for_string_array) g_dbus_variant_new_for_string_array __attribute((alias("IA__g_dbus_variant_new_for_string_array"), visibility("default")));

#undef g_dbus_variant_new_for_structure 
extern __typeof (g_dbus_variant_new_for_structure) g_dbus_variant_new_for_structure __attribute((alias("IA__g_dbus_variant_new_for_structure"), visibility("default")));

#undef g_dbus_variant_new_for_variant 
extern __typeof (g_dbus_variant_new_for_variant) g_dbus_variant_new_for_variant __attribute((alias("IA__g_dbus_variant_new_for_variant"), visibility("default")));

#undef g_dbus_variant_new_for_uint 
extern __typeof (g_dbus_variant_new_for_uint) g_dbus_variant_new_for_uint __attribute((alias("IA__g_dbus_variant_new_for_uint"), visibility("default")));

#undef g_dbus_variant_new_for_uint16 
extern __typeof (g_dbus_variant_new_for_uint16) g_dbus_variant_new_for_uint16 __attribute((alias("IA__g_dbus_variant_new_for_uint16"), visibility("default")));

#undef g_dbus_variant_new_for_uint64 
extern __typeof (g_dbus_variant_new_for_uint64) g_dbus_variant_new_for_uint64 __attribute((alias("IA__g_dbus_variant_new_for_uint64"), visibility("default")));

#undef g_dbus_variant_set_array 
extern __typeof (g_dbus_variant_set_array) g_dbus_variant_set_array __attribute((alias("IA__g_dbus_variant_set_array"), visibility("default")));

#undef g_dbus_variant_set_boolean 
extern __typeof (g_dbus_variant_set_boolean) g_dbus_variant_set_boolean __attribute((alias("IA__g_dbus_variant_set_boolean"), visibility("default")));

#undef g_dbus_variant_set_byte 
extern __typeof (g_dbus_variant_set_byte) g_dbus_variant_set_byte __attribute((alias("IA__g_dbus_variant_set_byte"), visibility("default")));

#undef g_dbus_variant_set_double 
extern __typeof (g_dbus_variant_set_double) g_dbus_variant_set_double __attribute((alias("IA__g_dbus_variant_set_double"), visibility("default")));

#undef g_dbus_variant_set_hash_table 
extern __typeof (g_dbus_variant_set_hash_table) g_dbus_variant_set_hash_table __attribute((alias("IA__g_dbus_variant_set_hash_table"), visibility("default")));

#undef g_dbus_variant_set_int 
extern __typeof (g_dbus_variant_set_int) g_dbus_variant_set_int __attribute((alias("IA__g_dbus_variant_set_int"), visibility("default")));

#undef g_dbus_variant_set_int16 
extern __typeof (g_dbus_variant_set_int16) g_dbus_variant_set_int16 __attribute((alias("IA__g_dbus_variant_set_int16"), visibility("default")));

#undef g_dbus_variant_set_int64 
extern __typeof (g_dbus_variant_set_int64) g_dbus_variant_set_int64 __attribute((alias("IA__g_dbus_variant_set_int64"), visibility("default")));

#undef g_dbus_variant_set_object_path 
extern __typeof (g_dbus_variant_set_object_path) g_dbus_variant_set_object_path __attribute((alias("IA__g_dbus_variant_set_object_path"), visibility("default")));

#undef g_dbus_variant_set_object_path_array 
extern __typeof (g_dbus_variant_set_object_path_array) g_dbus_variant_set_object_path_array __attribute((alias("IA__g_dbus_variant_set_object_path_array"), visibility("default")));

#undef g_dbus_variant_set_ptr_array 
extern __typeof (g_dbus_variant_set_ptr_array) g_dbus_variant_set_ptr_array __attribute((alias("IA__g_dbus_variant_set_ptr_array"), visibility("default")));

#undef g_dbus_variant_set_signature 
extern __typeof (g_dbus_variant_set_signature) g_dbus_variant_set_signature __attribute((alias("IA__g_dbus_variant_set_signature"), visibility("default")));

#undef g_dbus_variant_set_signature_array 
extern __typeof (g_dbus_variant_set_signature_array) g_dbus_variant_set_signature_array __attribute((alias("IA__g_dbus_variant_set_signature_array"), visibility("default")));

#undef g_dbus_variant_set_string 
extern __typeof (g_dbus_variant_set_string) g_dbus_variant_set_string __attribute((alias("IA__g_dbus_variant_set_string"), visibility("default")));

#undef g_dbus_variant_set_string_array 
extern __typeof (g_dbus_variant_set_string_array) g_dbus_variant_set_string_array __attribute((alias("IA__g_dbus_variant_set_string_array"), visibility("default")));

#undef g_dbus_variant_set_structure 
extern __typeof (g_dbus_variant_set_structure) g_dbus_variant_set_structure __attribute((alias("IA__g_dbus_variant_set_structure"), visibility("default")));

#undef g_dbus_variant_set_variant 
extern __typeof (g_dbus_variant_set_variant) g_dbus_variant_set_variant __attribute((alias("IA__g_dbus_variant_set_variant"), visibility("default")));

#undef g_dbus_variant_set_uint 
extern __typeof (g_dbus_variant_set_uint) g_dbus_variant_set_uint __attribute((alias("IA__g_dbus_variant_set_uint"), visibility("default")));

#undef g_dbus_variant_set_uint16 
extern __typeof (g_dbus_variant_set_uint16) g_dbus_variant_set_uint16 __attribute((alias("IA__g_dbus_variant_set_uint16"), visibility("default")));

#undef g_dbus_variant_set_uint64 
extern __typeof (g_dbus_variant_set_uint64) g_dbus_variant_set_uint64 __attribute((alias("IA__g_dbus_variant_set_uint64"), visibility("default")));

#endif
#endif

#endif /* G_HAVE_GNUC_VISIBILITY */
#endif /* DISABLE_VISIBILITY */
