/* Generated by makegdbusalias.pl */

#ifndef DISABLE_VISIBILITY

#include "glib.h"

#ifdef G_HAVE_GNUC_VISIBILITY

#define IN_FILE(x) 1
#define IN_HEADER defined

#if IN_HEADER(__G_DBUS_CONNECTION_H__)
#if IN_FILE(__G_DBUS_CONNECTION_C__)
extern __typeof (g_dbus_connection_get_type) IA__g_dbus_connection_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_dbus_connection_get_type IA__g_dbus_connection_get_type

extern __typeof (g_dbus_connection_bus_get) IA__g_dbus_connection_bus_get __attribute((visibility("hidden")));
#define g_dbus_connection_bus_get IA__g_dbus_connection_bus_get

extern __typeof (g_dbus_connection_bus_get_private) IA__g_dbus_connection_bus_get_private __attribute((visibility("hidden")));
#define g_dbus_connection_bus_get_private IA__g_dbus_connection_bus_get_private

extern __typeof (g_dbus_connection_get_unique_name) IA__g_dbus_connection_get_unique_name __attribute((visibility("hidden")));
#define g_dbus_connection_get_unique_name IA__g_dbus_connection_get_unique_name

extern __typeof (g_dbus_connection_get_is_open) IA__g_dbus_connection_get_is_open __attribute((visibility("hidden")));
#define g_dbus_connection_get_is_open IA__g_dbus_connection_get_is_open

extern __typeof (g_dbus_connection_get_is_private) IA__g_dbus_connection_get_is_private __attribute((visibility("hidden")));
#define g_dbus_connection_get_is_private IA__g_dbus_connection_get_is_private

extern __typeof (g_dbus_connection_get_bus_type) IA__g_dbus_connection_get_bus_type __attribute((visibility("hidden")));
#define g_dbus_connection_get_bus_type IA__g_dbus_connection_get_bus_type

extern __typeof (g_dbus_connection_get_exit_on_close) IA__g_dbus_connection_get_exit_on_close __attribute((visibility("hidden")));
#define g_dbus_connection_get_exit_on_close IA__g_dbus_connection_get_exit_on_close

extern __typeof (g_dbus_connection_set_exit_on_close) IA__g_dbus_connection_set_exit_on_close __attribute((visibility("hidden")));
#define g_dbus_connection_set_exit_on_close IA__g_dbus_connection_set_exit_on_close

extern __typeof (g_dbus_connection_get_is_initialized) IA__g_dbus_connection_get_is_initialized __attribute((visibility("hidden")));
#define g_dbus_connection_get_is_initialized IA__g_dbus_connection_get_is_initialized

extern __typeof (g_dbus_connection_signal_subscribe) IA__g_dbus_connection_signal_subscribe __attribute((visibility("hidden")));
#define g_dbus_connection_signal_subscribe IA__g_dbus_connection_signal_subscribe

extern __typeof (g_dbus_connection_signal_unsubscribe) IA__g_dbus_connection_signal_unsubscribe __attribute((visibility("hidden")));
#define g_dbus_connection_signal_unsubscribe IA__g_dbus_connection_signal_unsubscribe

#endif
#endif
#if IN_HEADER(__G_DBUS_CONNECTION_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_CONNECTION_C__)
extern __typeof (g_dbus_connection_get_dbus_1_connection) IA__g_dbus_connection_get_dbus_1_connection __attribute((visibility("hidden")));
#define g_dbus_connection_get_dbus_1_connection IA__g_dbus_connection_get_dbus_1_connection

extern __typeof (g_dbus_connection_send_dbus_1_message) IA__g_dbus_connection_send_dbus_1_message __attribute((visibility("hidden")));
#define g_dbus_connection_send_dbus_1_message IA__g_dbus_connection_send_dbus_1_message

extern __typeof (g_dbus_connection_send_dbus_1_message_with_reply) IA__g_dbus_connection_send_dbus_1_message_with_reply __attribute((visibility("hidden")));
#define g_dbus_connection_send_dbus_1_message_with_reply IA__g_dbus_connection_send_dbus_1_message_with_reply

extern __typeof (g_dbus_connection_send_dbus_1_message_with_reply_finish) IA__g_dbus_connection_send_dbus_1_message_with_reply_finish __attribute((visibility("hidden")));
#define g_dbus_connection_send_dbus_1_message_with_reply_finish IA__g_dbus_connection_send_dbus_1_message_with_reply_finish

extern __typeof (g_dbus_connection_send_dbus_1_message_with_reply_sync) IA__g_dbus_connection_send_dbus_1_message_with_reply_sync __attribute((visibility("hidden")));
#define g_dbus_connection_send_dbus_1_message_with_reply_sync IA__g_dbus_connection_send_dbus_1_message_with_reply_sync

extern __typeof (g_dbus_connection_dbus_1_signal_subscribe) IA__g_dbus_connection_dbus_1_signal_subscribe __attribute((visibility("hidden")));
#define g_dbus_connection_dbus_1_signal_subscribe IA__g_dbus_connection_dbus_1_signal_subscribe

extern __typeof (g_dbus_connection_dbus_1_signal_unsubscribe) IA__g_dbus_connection_dbus_1_signal_unsubscribe __attribute((visibility("hidden")));
#define g_dbus_connection_dbus_1_signal_unsubscribe IA__g_dbus_connection_dbus_1_signal_unsubscribe

#endif
#endif
#if IN_HEADER(__G_DBUS_C_TYPE_MAPPING_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_C_TYPE_MAPPING_C__)
extern __typeof (g_dbus_c_type_mapping_get_value_from_iter) IA__g_dbus_c_type_mapping_get_value_from_iter __attribute((visibility("hidden")));
#define g_dbus_c_type_mapping_get_value_from_iter IA__g_dbus_c_type_mapping_get_value_from_iter

extern __typeof (g_dbus_c_type_mapping_append_value_to_iter) IA__g_dbus_c_type_mapping_append_value_to_iter __attribute((visibility("hidden")));
#define g_dbus_c_type_mapping_append_value_to_iter IA__g_dbus_c_type_mapping_append_value_to_iter

#endif
#endif
#if IN_HEADER(__G_DBUS_MAINLOOP_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_MAINLOOP_C__)
extern __typeof (g_dbus_integrate_dbus_1_connection) IA__g_dbus_integrate_dbus_1_connection __attribute((visibility("hidden")));
#define g_dbus_integrate_dbus_1_connection IA__g_dbus_integrate_dbus_1_connection

extern __typeof (g_dbus_unintegrate_dbus_1_connection) IA__g_dbus_unintegrate_dbus_1_connection __attribute((visibility("hidden")));
#define g_dbus_unintegrate_dbus_1_connection IA__g_dbus_unintegrate_dbus_1_connection

extern __typeof (g_dbus_integrate_dbus_1_server) IA__g_dbus_integrate_dbus_1_server __attribute((visibility("hidden")));
#define g_dbus_integrate_dbus_1_server IA__g_dbus_integrate_dbus_1_server

extern __typeof (g_dbus_unintegrate_dbus_1_server) IA__g_dbus_unintegrate_dbus_1_server __attribute((visibility("hidden")));
#define g_dbus_unintegrate_dbus_1_server IA__g_dbus_unintegrate_dbus_1_server

#endif
#endif
#if IN_HEADER(__G_BUS_NAME_OWNER_H__)
#if IN_FILE(__G_BUS_NAME_OWNER_C__)
extern __typeof (g_bus_name_owner_get_type) IA__g_bus_name_owner_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_bus_name_owner_get_type IA__g_bus_name_owner_get_type

extern __typeof (g_bus_name_owner_new) IA__g_bus_name_owner_new __attribute((visibility("hidden")));
#define g_bus_name_owner_new IA__g_bus_name_owner_new

extern __typeof (g_bus_name_owner_new_for_connection) IA__g_bus_name_owner_new_for_connection __attribute((visibility("hidden")));
#define g_bus_name_owner_new_for_connection IA__g_bus_name_owner_new_for_connection

extern __typeof (g_bus_name_owner_get_owns_name) IA__g_bus_name_owner_get_owns_name __attribute((visibility("hidden")));
#define g_bus_name_owner_get_owns_name IA__g_bus_name_owner_get_owns_name

extern __typeof (g_bus_name_owner_get_name) IA__g_bus_name_owner_get_name __attribute((visibility("hidden")));
#define g_bus_name_owner_get_name IA__g_bus_name_owner_get_name

extern __typeof (g_bus_name_owner_get_bus_type) IA__g_bus_name_owner_get_bus_type __attribute((visibility("hidden")));
#define g_bus_name_owner_get_bus_type IA__g_bus_name_owner_get_bus_type

extern __typeof (g_bus_name_owner_get_flags) IA__g_bus_name_owner_get_flags __attribute((visibility("hidden")));
#define g_bus_name_owner_get_flags IA__g_bus_name_owner_get_flags

extern __typeof (g_bus_name_owner_get_is_initialized) IA__g_bus_name_owner_get_is_initialized __attribute((visibility("hidden")));
#define g_bus_name_owner_get_is_initialized IA__g_bus_name_owner_get_is_initialized

extern __typeof (g_bus_name_owner_get_connection) IA__g_bus_name_owner_get_connection __attribute((visibility("hidden")));
#define g_bus_name_owner_get_connection IA__g_bus_name_owner_get_connection

#endif
#endif
#if IN_HEADER(__G_BUS_NAME_WATCHER_H__)
#if IN_FILE(__G_BUS_NAME_WATCHER_C__)
extern __typeof (g_bus_name_watcher_get_type) IA__g_bus_name_watcher_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_bus_name_watcher_get_type IA__g_bus_name_watcher_get_type

extern __typeof (g_bus_name_watcher_new) IA__g_bus_name_watcher_new __attribute((visibility("hidden")));
#define g_bus_name_watcher_new IA__g_bus_name_watcher_new

extern __typeof (g_bus_name_watcher_new_for_connection) IA__g_bus_name_watcher_new_for_connection __attribute((visibility("hidden")));
#define g_bus_name_watcher_new_for_connection IA__g_bus_name_watcher_new_for_connection

extern __typeof (g_bus_name_watcher_get_name_owner) IA__g_bus_name_watcher_get_name_owner __attribute((visibility("hidden")));
#define g_bus_name_watcher_get_name_owner IA__g_bus_name_watcher_get_name_owner

extern __typeof (g_bus_name_watcher_get_name) IA__g_bus_name_watcher_get_name __attribute((visibility("hidden")));
#define g_bus_name_watcher_get_name IA__g_bus_name_watcher_get_name

extern __typeof (g_bus_name_watcher_get_bus_type) IA__g_bus_name_watcher_get_bus_type __attribute((visibility("hidden")));
#define g_bus_name_watcher_get_bus_type IA__g_bus_name_watcher_get_bus_type

extern __typeof (g_bus_name_watcher_get_is_initialized) IA__g_bus_name_watcher_get_is_initialized __attribute((visibility("hidden")));
#define g_bus_name_watcher_get_is_initialized IA__g_bus_name_watcher_get_is_initialized

extern __typeof (g_bus_name_watcher_get_connection) IA__g_bus_name_watcher_get_connection __attribute((visibility("hidden")));
#define g_bus_name_watcher_get_connection IA__g_bus_name_watcher_get_connection

#endif
#endif
#if IN_HEADER(__G_DBUS_ENUM_TYPES_H__)
#if IN_FILE(__G_DBUS_ENUM_TYPES_C__)
extern __typeof (g_dbus_error_get_type) IA__g_dbus_error_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_dbus_error_get_type IA__g_dbus_error_get_type

extern __typeof (g_bus_type_get_type) IA__g_bus_type_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_bus_type_get_type IA__g_bus_type_get_type

extern __typeof (g_bus_name_owner_flags_get_type) IA__g_bus_name_owner_flags_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_bus_name_owner_flags_get_type IA__g_bus_name_owner_flags_get_type

extern __typeof (g_dbus_proxy_flags_get_type) IA__g_dbus_proxy_flags_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_dbus_proxy_flags_get_type IA__g_dbus_proxy_flags_get_type

#endif
#endif
#if IN_HEADER(__G_DBUS_ERROR_H__)
#if IN_FILE(__G_DBUS_ERROR_C__)
extern __typeof (g_dbus_error_quark) IA__g_dbus_error_quark __attribute((visibility("hidden")));
#define g_dbus_error_quark IA__g_dbus_error_quark

extern __typeof (g_dbus_error_get_remote_exception) IA__g_dbus_error_get_remote_exception __attribute((visibility("hidden")));
#define g_dbus_error_get_remote_exception IA__g_dbus_error_get_remote_exception

#endif
#endif
#if IN_HEADER(__G_DBUS_ERROR_LOWLEVEL_H__)
#if IN_FILE(__G_DBUS_ERROR_C__)
extern __typeof (g_dbus_error_new_for_dbus_error) IA__g_dbus_error_new_for_dbus_error __attribute((visibility("hidden")));
#define g_dbus_error_new_for_dbus_error IA__g_dbus_error_new_for_dbus_error

extern __typeof (g_dbus_error_new_for_dbus_error_valist) IA__g_dbus_error_new_for_dbus_error_valist __attribute((visibility("hidden")));
#define g_dbus_error_new_for_dbus_error_valist IA__g_dbus_error_new_for_dbus_error_valist

extern __typeof (g_dbus_error_new_for_gerror) IA__g_dbus_error_new_for_gerror __attribute((visibility("hidden")));
#define g_dbus_error_new_for_gerror IA__g_dbus_error_new_for_gerror

extern __typeof (g_dbus_error_set_dbus_error) IA__g_dbus_error_set_dbus_error __attribute((visibility("hidden")));
#define g_dbus_error_set_dbus_error IA__g_dbus_error_set_dbus_error

extern __typeof (g_dbus_error_set_dbus_error_valist) IA__g_dbus_error_set_dbus_error_valist __attribute((visibility("hidden")));
#define g_dbus_error_set_dbus_error_valist IA__g_dbus_error_set_dbus_error_valist

#endif
#endif
#if IN_HEADER(__G_DBUS_NAME_WATCHING_H__)
#if IN_FILE(__G_DBUS_NAME_WATCHING_C__)
extern __typeof (g_bus_watch_name) IA__g_bus_watch_name __attribute((visibility("hidden")));
#define g_bus_watch_name IA__g_bus_watch_name

extern __typeof (g_bus_unwatch_name) IA__g_bus_unwatch_name __attribute((visibility("hidden")));
#define g_bus_unwatch_name IA__g_bus_unwatch_name

#endif
#endif
#if IN_HEADER(__G_DBUS_PROXY_WATCHING_H__)
#if IN_FILE(__G_DBUS_PROXY_WATCHING_C__)
extern __typeof (g_bus_watch_proxy) IA__g_bus_watch_proxy __attribute((visibility("hidden")));
#define g_bus_watch_proxy IA__g_bus_watch_proxy

extern __typeof (g_bus_unwatch_proxy) IA__g_bus_unwatch_proxy __attribute((visibility("hidden")));
#define g_bus_unwatch_proxy IA__g_bus_unwatch_proxy

#endif
#endif
#if IN_HEADER(__G_DBUS_NAME_OWNING_H__)
#if IN_FILE(__G_DBUS_NAME_OWNING_C__)
extern __typeof (g_bus_own_name) IA__g_bus_own_name __attribute((visibility("hidden")));
#define g_bus_own_name IA__g_bus_own_name

extern __typeof (g_bus_unown_name) IA__g_bus_unown_name __attribute((visibility("hidden")));
#define g_bus_unown_name IA__g_bus_unown_name

#endif
#endif
#if IN_HEADER(__G_DBUS_PROXY_H__)
#if IN_FILE(__G_DBUS_PROXY_C__)
extern __typeof (g_dbus_proxy_get_type) IA__g_dbus_proxy_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_dbus_proxy_get_type IA__g_dbus_proxy_get_type

extern __typeof (g_dbus_proxy_new) IA__g_dbus_proxy_new __attribute((visibility("hidden")));
#define g_dbus_proxy_new IA__g_dbus_proxy_new

extern __typeof (g_dbus_proxy_new_finish) IA__g_dbus_proxy_new_finish __attribute((visibility("hidden")));
#define g_dbus_proxy_new_finish IA__g_dbus_proxy_new_finish

extern __typeof (g_dbus_proxy_new_sync) IA__g_dbus_proxy_new_sync __attribute((visibility("hidden")));
#define g_dbus_proxy_new_sync IA__g_dbus_proxy_new_sync

extern __typeof (g_dbus_proxy_get_flags) IA__g_dbus_proxy_get_flags __attribute((visibility("hidden")));
#define g_dbus_proxy_get_flags IA__g_dbus_proxy_get_flags

extern __typeof (g_dbus_proxy_get_unique_bus_name) IA__g_dbus_proxy_get_unique_bus_name __attribute((visibility("hidden")));
#define g_dbus_proxy_get_unique_bus_name IA__g_dbus_proxy_get_unique_bus_name

extern __typeof (g_dbus_proxy_get_object_path) IA__g_dbus_proxy_get_object_path __attribute((visibility("hidden")));
#define g_dbus_proxy_get_object_path IA__g_dbus_proxy_get_object_path

extern __typeof (g_dbus_proxy_get_interface_name) IA__g_dbus_proxy_get_interface_name __attribute((visibility("hidden")));
#define g_dbus_proxy_get_interface_name IA__g_dbus_proxy_get_interface_name

extern __typeof (g_dbus_proxy_get_connection) IA__g_dbus_proxy_get_connection __attribute((visibility("hidden")));
#define g_dbus_proxy_get_connection IA__g_dbus_proxy_get_connection

extern __typeof (g_dbus_proxy_invoke_method) IA__g_dbus_proxy_invoke_method __attribute((visibility("hidden")));
#define g_dbus_proxy_invoke_method IA__g_dbus_proxy_invoke_method

extern __typeof (g_dbus_proxy_invoke_method_finish) IA__g_dbus_proxy_invoke_method_finish __attribute((visibility("hidden")));
#define g_dbus_proxy_invoke_method_finish IA__g_dbus_proxy_invoke_method_finish

extern __typeof (g_dbus_proxy_invoke_method_sync) IA__g_dbus_proxy_invoke_method_sync __attribute((visibility("hidden")));
#define g_dbus_proxy_invoke_method_sync IA__g_dbus_proxy_invoke_method_sync

extern __typeof (g_dbus_proxy_get_cached_property) IA__g_dbus_proxy_get_cached_property __attribute((visibility("hidden")));
#define g_dbus_proxy_get_cached_property IA__g_dbus_proxy_get_cached_property

#endif
#endif
#if IN_HEADER(__G_DBUS_STRUCTURE_H__)
#if IN_FILE(__G_DBUS_STRUCTURE_C__)
extern __typeof (g_dbus_structure_get_type) IA__g_dbus_structure_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_dbus_structure_get_type IA__g_dbus_structure_get_type

extern __typeof (g_dbus_structure_equal) IA__g_dbus_structure_equal __attribute((visibility("hidden")));
#define g_dbus_structure_equal IA__g_dbus_structure_equal

extern __typeof (g_dbus_structure_get_element) IA__g_dbus_structure_get_element __attribute((visibility("hidden")));
#define g_dbus_structure_get_element IA__g_dbus_structure_get_element

extern __typeof (g_dbus_structure_get_num_elements) IA__g_dbus_structure_get_num_elements __attribute((visibility("hidden")));
#define g_dbus_structure_get_num_elements IA__g_dbus_structure_get_num_elements

extern __typeof (g_dbus_structure_get_signature) IA__g_dbus_structure_get_signature __attribute((visibility("hidden")));
#define g_dbus_structure_get_signature IA__g_dbus_structure_get_signature

extern __typeof (g_dbus_structure_get_signature_for_element) IA__g_dbus_structure_get_signature_for_element __attribute((visibility("hidden")));
#define g_dbus_structure_get_signature_for_element IA__g_dbus_structure_get_signature_for_element

extern __typeof (g_dbus_structure_new) IA__g_dbus_structure_new __attribute((visibility("hidden")));
#define g_dbus_structure_new IA__g_dbus_structure_new

extern __typeof (g_dbus_structure_set_element) IA__g_dbus_structure_set_element __attribute((visibility("hidden")));
#define g_dbus_structure_set_element IA__g_dbus_structure_set_element

#endif
#endif
#if IN_HEADER(__G_DBUS_VARIANT_H__)
#if IN_FILE(__G_DBUS_VARIANT_C__)
extern __typeof (g_dbus_variant_get_type) IA__g_dbus_variant_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define g_dbus_variant_get_type IA__g_dbus_variant_get_type

extern __typeof (g_dbus_variant_equal) IA__g_dbus_variant_equal __attribute((visibility("hidden")));
#define g_dbus_variant_equal IA__g_dbus_variant_equal

extern __typeof (g_dbus_variant_get_array) IA__g_dbus_variant_get_array __attribute((visibility("hidden")));
#define g_dbus_variant_get_array IA__g_dbus_variant_get_array

extern __typeof (g_dbus_variant_get_boolean) IA__g_dbus_variant_get_boolean __attribute((visibility("hidden")));
#define g_dbus_variant_get_boolean IA__g_dbus_variant_get_boolean

extern __typeof (g_dbus_variant_get_byte) IA__g_dbus_variant_get_byte __attribute((visibility("hidden")));
#define g_dbus_variant_get_byte IA__g_dbus_variant_get_byte

extern __typeof (g_dbus_variant_get_double) IA__g_dbus_variant_get_double __attribute((visibility("hidden")));
#define g_dbus_variant_get_double IA__g_dbus_variant_get_double

extern __typeof (g_dbus_variant_get_hash_table) IA__g_dbus_variant_get_hash_table __attribute((visibility("hidden")));
#define g_dbus_variant_get_hash_table IA__g_dbus_variant_get_hash_table

extern __typeof (g_dbus_variant_get_int) IA__g_dbus_variant_get_int __attribute((visibility("hidden")));
#define g_dbus_variant_get_int IA__g_dbus_variant_get_int

extern __typeof (g_dbus_variant_get_int16) IA__g_dbus_variant_get_int16 __attribute((visibility("hidden")));
#define g_dbus_variant_get_int16 IA__g_dbus_variant_get_int16

extern __typeof (g_dbus_variant_get_int64) IA__g_dbus_variant_get_int64 __attribute((visibility("hidden")));
#define g_dbus_variant_get_int64 IA__g_dbus_variant_get_int64

extern __typeof (g_dbus_variant_get_object_path) IA__g_dbus_variant_get_object_path __attribute((visibility("hidden")));
#define g_dbus_variant_get_object_path IA__g_dbus_variant_get_object_path

extern __typeof (g_dbus_variant_get_object_path_array) IA__g_dbus_variant_get_object_path_array __attribute((visibility("hidden")));
#define g_dbus_variant_get_object_path_array IA__g_dbus_variant_get_object_path_array

extern __typeof (g_dbus_variant_get_ptr_array) IA__g_dbus_variant_get_ptr_array __attribute((visibility("hidden")));
#define g_dbus_variant_get_ptr_array IA__g_dbus_variant_get_ptr_array

extern __typeof (g_dbus_variant_get_signature) IA__g_dbus_variant_get_signature __attribute((visibility("hidden")));
#define g_dbus_variant_get_signature IA__g_dbus_variant_get_signature

extern __typeof (g_dbus_variant_get_signature_array) IA__g_dbus_variant_get_signature_array __attribute((visibility("hidden")));
#define g_dbus_variant_get_signature_array IA__g_dbus_variant_get_signature_array

extern __typeof (g_dbus_variant_get_string) IA__g_dbus_variant_get_string __attribute((visibility("hidden")));
#define g_dbus_variant_get_string IA__g_dbus_variant_get_string

extern __typeof (g_dbus_variant_get_string_array) IA__g_dbus_variant_get_string_array __attribute((visibility("hidden")));
#define g_dbus_variant_get_string_array IA__g_dbus_variant_get_string_array

extern __typeof (g_dbus_variant_get_structure) IA__g_dbus_variant_get_structure __attribute((visibility("hidden")));
#define g_dbus_variant_get_structure IA__g_dbus_variant_get_structure

extern __typeof (g_dbus_variant_get_variant) IA__g_dbus_variant_get_variant __attribute((visibility("hidden")));
#define g_dbus_variant_get_variant IA__g_dbus_variant_get_variant

extern __typeof (g_dbus_variant_get_uint) IA__g_dbus_variant_get_uint __attribute((visibility("hidden")));
#define g_dbus_variant_get_uint IA__g_dbus_variant_get_uint

extern __typeof (g_dbus_variant_get_uint16) IA__g_dbus_variant_get_uint16 __attribute((visibility("hidden")));
#define g_dbus_variant_get_uint16 IA__g_dbus_variant_get_uint16

extern __typeof (g_dbus_variant_get_uint64) IA__g_dbus_variant_get_uint64 __attribute((visibility("hidden")));
#define g_dbus_variant_get_uint64 IA__g_dbus_variant_get_uint64

extern __typeof (g_dbus_variant_get_variant_signature) IA__g_dbus_variant_get_variant_signature __attribute((visibility("hidden")));
#define g_dbus_variant_get_variant_signature IA__g_dbus_variant_get_variant_signature

extern __typeof (g_dbus_variant_is_array) IA__g_dbus_variant_is_array __attribute((visibility("hidden")));
#define g_dbus_variant_is_array IA__g_dbus_variant_is_array

extern __typeof (g_dbus_variant_is_boolean) IA__g_dbus_variant_is_boolean __attribute((visibility("hidden")));
#define g_dbus_variant_is_boolean IA__g_dbus_variant_is_boolean

extern __typeof (g_dbus_variant_is_byte) IA__g_dbus_variant_is_byte __attribute((visibility("hidden")));
#define g_dbus_variant_is_byte IA__g_dbus_variant_is_byte

extern __typeof (g_dbus_variant_is_double) IA__g_dbus_variant_is_double __attribute((visibility("hidden")));
#define g_dbus_variant_is_double IA__g_dbus_variant_is_double

extern __typeof (g_dbus_variant_is_hash_table) IA__g_dbus_variant_is_hash_table __attribute((visibility("hidden")));
#define g_dbus_variant_is_hash_table IA__g_dbus_variant_is_hash_table

extern __typeof (g_dbus_variant_is_int) IA__g_dbus_variant_is_int __attribute((visibility("hidden")));
#define g_dbus_variant_is_int IA__g_dbus_variant_is_int

extern __typeof (g_dbus_variant_is_int16) IA__g_dbus_variant_is_int16 __attribute((visibility("hidden")));
#define g_dbus_variant_is_int16 IA__g_dbus_variant_is_int16

extern __typeof (g_dbus_variant_is_int64) IA__g_dbus_variant_is_int64 __attribute((visibility("hidden")));
#define g_dbus_variant_is_int64 IA__g_dbus_variant_is_int64

extern __typeof (g_dbus_variant_is_object_path) IA__g_dbus_variant_is_object_path __attribute((visibility("hidden")));
#define g_dbus_variant_is_object_path IA__g_dbus_variant_is_object_path

extern __typeof (g_dbus_variant_is_object_path_array) IA__g_dbus_variant_is_object_path_array __attribute((visibility("hidden")));
#define g_dbus_variant_is_object_path_array IA__g_dbus_variant_is_object_path_array

extern __typeof (g_dbus_variant_is_ptr_array) IA__g_dbus_variant_is_ptr_array __attribute((visibility("hidden")));
#define g_dbus_variant_is_ptr_array IA__g_dbus_variant_is_ptr_array

extern __typeof (g_dbus_variant_is_signature) IA__g_dbus_variant_is_signature __attribute((visibility("hidden")));
#define g_dbus_variant_is_signature IA__g_dbus_variant_is_signature

extern __typeof (g_dbus_variant_is_signature_array) IA__g_dbus_variant_is_signature_array __attribute((visibility("hidden")));
#define g_dbus_variant_is_signature_array IA__g_dbus_variant_is_signature_array

extern __typeof (g_dbus_variant_is_string) IA__g_dbus_variant_is_string __attribute((visibility("hidden")));
#define g_dbus_variant_is_string IA__g_dbus_variant_is_string

extern __typeof (g_dbus_variant_is_string_array) IA__g_dbus_variant_is_string_array __attribute((visibility("hidden")));
#define g_dbus_variant_is_string_array IA__g_dbus_variant_is_string_array

extern __typeof (g_dbus_variant_is_structure) IA__g_dbus_variant_is_structure __attribute((visibility("hidden")));
#define g_dbus_variant_is_structure IA__g_dbus_variant_is_structure

extern __typeof (g_dbus_variant_is_variant) IA__g_dbus_variant_is_variant __attribute((visibility("hidden")));
#define g_dbus_variant_is_variant IA__g_dbus_variant_is_variant

extern __typeof (g_dbus_variant_is_uint) IA__g_dbus_variant_is_uint __attribute((visibility("hidden")));
#define g_dbus_variant_is_uint IA__g_dbus_variant_is_uint

extern __typeof (g_dbus_variant_is_uint16) IA__g_dbus_variant_is_uint16 __attribute((visibility("hidden")));
#define g_dbus_variant_is_uint16 IA__g_dbus_variant_is_uint16

extern __typeof (g_dbus_variant_is_uint64) IA__g_dbus_variant_is_uint64 __attribute((visibility("hidden")));
#define g_dbus_variant_is_uint64 IA__g_dbus_variant_is_uint64

extern __typeof (g_dbus_variant_is_unset) IA__g_dbus_variant_is_unset __attribute((visibility("hidden")));
#define g_dbus_variant_is_unset IA__g_dbus_variant_is_unset

extern __typeof (g_dbus_variant_new) IA__g_dbus_variant_new __attribute((visibility("hidden")));
#define g_dbus_variant_new IA__g_dbus_variant_new

extern __typeof (g_dbus_variant_new_for_array) IA__g_dbus_variant_new_for_array __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_array IA__g_dbus_variant_new_for_array

extern __typeof (g_dbus_variant_new_for_boolean) IA__g_dbus_variant_new_for_boolean __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_boolean IA__g_dbus_variant_new_for_boolean

extern __typeof (g_dbus_variant_new_for_byte) IA__g_dbus_variant_new_for_byte __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_byte IA__g_dbus_variant_new_for_byte

extern __typeof (g_dbus_variant_new_for_double) IA__g_dbus_variant_new_for_double __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_double IA__g_dbus_variant_new_for_double

extern __typeof (g_dbus_variant_new_for_hash_table) IA__g_dbus_variant_new_for_hash_table __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_hash_table IA__g_dbus_variant_new_for_hash_table

extern __typeof (g_dbus_variant_new_for_int) IA__g_dbus_variant_new_for_int __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_int IA__g_dbus_variant_new_for_int

extern __typeof (g_dbus_variant_new_for_int16) IA__g_dbus_variant_new_for_int16 __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_int16 IA__g_dbus_variant_new_for_int16

extern __typeof (g_dbus_variant_new_for_int64) IA__g_dbus_variant_new_for_int64 __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_int64 IA__g_dbus_variant_new_for_int64

extern __typeof (g_dbus_variant_new_for_object_path) IA__g_dbus_variant_new_for_object_path __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_object_path IA__g_dbus_variant_new_for_object_path

extern __typeof (g_dbus_variant_new_for_object_path_array) IA__g_dbus_variant_new_for_object_path_array __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_object_path_array IA__g_dbus_variant_new_for_object_path_array

extern __typeof (g_dbus_variant_new_for_ptr_array) IA__g_dbus_variant_new_for_ptr_array __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_ptr_array IA__g_dbus_variant_new_for_ptr_array

extern __typeof (g_dbus_variant_new_for_signature) IA__g_dbus_variant_new_for_signature __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_signature IA__g_dbus_variant_new_for_signature

extern __typeof (g_dbus_variant_new_for_signature_array) IA__g_dbus_variant_new_for_signature_array __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_signature_array IA__g_dbus_variant_new_for_signature_array

extern __typeof (g_dbus_variant_new_for_string) IA__g_dbus_variant_new_for_string __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_string IA__g_dbus_variant_new_for_string

extern __typeof (g_dbus_variant_new_for_string_array) IA__g_dbus_variant_new_for_string_array __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_string_array IA__g_dbus_variant_new_for_string_array

extern __typeof (g_dbus_variant_new_for_structure) IA__g_dbus_variant_new_for_structure __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_structure IA__g_dbus_variant_new_for_structure

extern __typeof (g_dbus_variant_new_for_variant) IA__g_dbus_variant_new_for_variant __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_variant IA__g_dbus_variant_new_for_variant

extern __typeof (g_dbus_variant_new_for_uint) IA__g_dbus_variant_new_for_uint __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_uint IA__g_dbus_variant_new_for_uint

extern __typeof (g_dbus_variant_new_for_uint16) IA__g_dbus_variant_new_for_uint16 __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_uint16 IA__g_dbus_variant_new_for_uint16

extern __typeof (g_dbus_variant_new_for_uint64) IA__g_dbus_variant_new_for_uint64 __attribute((visibility("hidden")));
#define g_dbus_variant_new_for_uint64 IA__g_dbus_variant_new_for_uint64

extern __typeof (g_dbus_variant_set_array) IA__g_dbus_variant_set_array __attribute((visibility("hidden")));
#define g_dbus_variant_set_array IA__g_dbus_variant_set_array

extern __typeof (g_dbus_variant_set_boolean) IA__g_dbus_variant_set_boolean __attribute((visibility("hidden")));
#define g_dbus_variant_set_boolean IA__g_dbus_variant_set_boolean

extern __typeof (g_dbus_variant_set_byte) IA__g_dbus_variant_set_byte __attribute((visibility("hidden")));
#define g_dbus_variant_set_byte IA__g_dbus_variant_set_byte

extern __typeof (g_dbus_variant_set_double) IA__g_dbus_variant_set_double __attribute((visibility("hidden")));
#define g_dbus_variant_set_double IA__g_dbus_variant_set_double

extern __typeof (g_dbus_variant_set_hash_table) IA__g_dbus_variant_set_hash_table __attribute((visibility("hidden")));
#define g_dbus_variant_set_hash_table IA__g_dbus_variant_set_hash_table

extern __typeof (g_dbus_variant_set_int) IA__g_dbus_variant_set_int __attribute((visibility("hidden")));
#define g_dbus_variant_set_int IA__g_dbus_variant_set_int

extern __typeof (g_dbus_variant_set_int16) IA__g_dbus_variant_set_int16 __attribute((visibility("hidden")));
#define g_dbus_variant_set_int16 IA__g_dbus_variant_set_int16

extern __typeof (g_dbus_variant_set_int64) IA__g_dbus_variant_set_int64 __attribute((visibility("hidden")));
#define g_dbus_variant_set_int64 IA__g_dbus_variant_set_int64

extern __typeof (g_dbus_variant_set_object_path) IA__g_dbus_variant_set_object_path __attribute((visibility("hidden")));
#define g_dbus_variant_set_object_path IA__g_dbus_variant_set_object_path

extern __typeof (g_dbus_variant_set_object_path_array) IA__g_dbus_variant_set_object_path_array __attribute((visibility("hidden")));
#define g_dbus_variant_set_object_path_array IA__g_dbus_variant_set_object_path_array

extern __typeof (g_dbus_variant_set_ptr_array) IA__g_dbus_variant_set_ptr_array __attribute((visibility("hidden")));
#define g_dbus_variant_set_ptr_array IA__g_dbus_variant_set_ptr_array

extern __typeof (g_dbus_variant_set_signature) IA__g_dbus_variant_set_signature __attribute((visibility("hidden")));
#define g_dbus_variant_set_signature IA__g_dbus_variant_set_signature

extern __typeof (g_dbus_variant_set_signature_array) IA__g_dbus_variant_set_signature_array __attribute((visibility("hidden")));
#define g_dbus_variant_set_signature_array IA__g_dbus_variant_set_signature_array

extern __typeof (g_dbus_variant_set_string) IA__g_dbus_variant_set_string __attribute((visibility("hidden")));
#define g_dbus_variant_set_string IA__g_dbus_variant_set_string

extern __typeof (g_dbus_variant_set_string_array) IA__g_dbus_variant_set_string_array __attribute((visibility("hidden")));
#define g_dbus_variant_set_string_array IA__g_dbus_variant_set_string_array

extern __typeof (g_dbus_variant_set_structure) IA__g_dbus_variant_set_structure __attribute((visibility("hidden")));
#define g_dbus_variant_set_structure IA__g_dbus_variant_set_structure

extern __typeof (g_dbus_variant_set_variant) IA__g_dbus_variant_set_variant __attribute((visibility("hidden")));
#define g_dbus_variant_set_variant IA__g_dbus_variant_set_variant

extern __typeof (g_dbus_variant_set_uint) IA__g_dbus_variant_set_uint __attribute((visibility("hidden")));
#define g_dbus_variant_set_uint IA__g_dbus_variant_set_uint

extern __typeof (g_dbus_variant_set_uint16) IA__g_dbus_variant_set_uint16 __attribute((visibility("hidden")));
#define g_dbus_variant_set_uint16 IA__g_dbus_variant_set_uint16

extern __typeof (g_dbus_variant_set_uint64) IA__g_dbus_variant_set_uint64 __attribute((visibility("hidden")));
#define g_dbus_variant_set_uint64 IA__g_dbus_variant_set_uint64

#endif
#endif

#endif /* G_HAVE_GNUC_VISIBILITY */
#endif /* DISABLE_VISIBILITY */
